### ISSUE TITLE
how to compile?

### ISSUE THREAD

**Issue by DocMAX** [flyingcircusio/check_journal#1]
how to compile?

**Comment by ckauhaus** [comment]
Python code does not need to be compiled. Install the nagiosplugin lib in a virtualenv and just use the script.

**Comment by addyess** [comment]
i'm sorry, but the project appears to be rust.  This could be a really great check if you provided a makefile that would build and publish.

**Comment by ckauhaus** [comment]
We've rewritten the tool in the meantime. Standard Rust build procedures apply. I'm updating the README. A Makefile already exists. I've included a install target.

@addyess How would you expect to have this plugin published?

**Comment by addyess** [comment]
I mean, if the package was available as a snap, this would be fantastic.  But thanks for providing the Makefile and updated README.  
Do you normally deploy this with nagios?  
if so, does the nagios user run this check?
if so, how do you get around the nagios user needed to run journalctl?

**Comment by ckauhaus** [comment]
Sorry, I have no clue on how to build a snap. :-/

The question about journal permissions is important. I'm adding a section on that to the README.

**Comment by addyess** [comment]
https://github.com/flyingcircusio/check_journal/pull/2 includes the necessary pieces to build a snap

**Comment by ckauhaus** [comment]
Awesome! I'll try that out during the weekend.

**Comment by ckauhaus** [comment]
Snap is [published](https://snapcraft.io/check-journal). 

For convenience, I've added a [statically compiled binary](https://github.com/flyingcircusio/check_journal/releases/tag/1.2.0).
